name: first

on: 
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.MY_API_KEY }}
    steps:
      - name: Trigger regression tests
        run: |
          gh workflow run build-projects.yaml \
          --repo "Supriya-kantipudi/g_act_pr" \
          -f commit_version=${{ github.sha }}
